In [2]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "wildfire"
    / "alberta_wildfires_2006_2025.csv"
)

df = pd.read_csv(DATA_PATH)

print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")

df.head()

Rows: 27,828
Columns: 50

,YEAR,FIRE_NUMBER,FIRE_NAME,CURRENT_SIZE,SIZE_CLASS,LATITUDE,LONGITUDE,FIRE_ORIGIN,GENERAL_CAUSE,INDUSTRY_IDENTIFIER,...,DISTANCE_FROM_WATER_SOURCE,FIRST_BUCKET_DROP_DATE,FIRST_BH_DATE,FIRST_BH_SIZE,FIRST_UC_DATE,FIRST_UC_SIZE,FIRST_TO_DATE,FIRST_TO_SIZE,FIRST_EX_DATE,FIRST_EX_SIZE_PERIMETER
0,2006,PWF001,NaN,0.10,A,56.249956,-117.181960,Private Land,Resident,NaN,...,NaN,NaN,2006-04-02 22:00,0.01,2006-04-02 22:00,0.01,NaN,NaN,2006-04-03 10:20,0.10
1,2006,EWF002,NaN,0.20,B,53.606367,-115.915733,Provincial Land,Incendiary,NaN,...,NaN,NaN,2006-04-03 13:20,0.20,2006-04-03 13:20,0.20,NaN,NaN,2006-04-03 14:00,0.20
2,2006,EWF001,NaN,0.50,B,53.610933,-115.594267,Provincial Land,Incendiary,NaN,...,NaN,NaN,2006-04-03 13:23,0.50,2006-04-03 13:23,0.50,NaN,NaN,2006-04-03 15:00,0.50
3,2006,EWF003,NaN,0.01,A,53.608867,-115.609467,Provincial Land,Incendiary,NaN,...,NaN,NaN,2006-04-03 14:08,0.01,2006-04-03 14:08,0.01,NaN,NaN,2006-04-03 15:05,0.01
4,2006,PWF002,NaN,0.10,A,56.249956,-117.050249,Provincial Land,Other Industry,Waste Disposal,...,NaN,NaN,2006-04-03 19:57,0.10,2006-04-03 20:19,0.10,2006-04-03 20:20,0.1,2006-04-05 10:18,0.10

In [3]:
df.info

<bound method DataFrame.info of        YEAR FIRE_NUMBER FIRE_NAME  CURRENT_SIZE SIZE_CLASS   LATITUDE  \
0      2006      PWF001       NaN          0.10          A  56.249956
1      2006      EWF002       NaN          0.20          B  53.606367
2      2006      EWF001       NaN          0.50          B  53.610933
3      2006      EWF003       NaN          0.01          A  53.608867
4      2006      PWF002       NaN          0.10          A  56.249956
...     ...         ...       ...           ...        ...        ...
27823  2025      LWF180       NaN          2.90          B  54.565633
27824  2024      LWF190       NaN          0.01          A  54.685967
27825  2024      HWF100       NaN        621.60          E  58.669333
27826  2024      HWF180       NaN          0.22          B  58.505333
27827  2024      WWF064       NaN          0.01          A  54.079033

        LONGITUDE         FIRE_ORIGIN         GENERAL_CAUSE  \
0     -117.181960        Private Land              Resident
1     -115.915733     Provincial Land            Incendiary
2     -115.594267     Provincial Land            Incendiary
3     -115.609467     Provincial Land            Incendiary
4     -117.050249     Provincial Land        Other Industry
...           ...                 ...                   ...
27823 -111.131967        Private Land  Agriculture Industry
27824 -111.874267  Indian Reservation            Incendiary
27825 -119.159033     Provincial Land             Lightning
27826 -115.131833     Provincial Land              Resident
27827 -115.553183        Private Land              Resident

      INDUSTRY_IDENTIFIER  ... DISTANCE_FROM_WATER_SOURCE  \
0                     NaN  ...                        NaN
1                     NaN  ...                        NaN
2                     NaN  ...                        NaN
3                     NaN  ...                        NaN
4          Waste Disposal  ...                        NaN
...                   ...  ...                        ...
27823                 NaN  ...                        NaN
27824                 NaN  ...                        2.0
27825                 NaN  ...                        1.1
27826                 NaN  ...                        NaN
27827                 NaN  ...                        NaN

      FIRST_BUCKET_DROP_DATE     FIRST_BH_DATE FIRST_BH_SIZE  \
0                        NaN  2006-04-02 22:00          0.01
1                        NaN  2006-04-03 13:20          0.20
2                        NaN  2006-04-03 13:23          0.50
3                        NaN  2006-04-03 14:08          0.01
4                        NaN  2006-04-03 19:57          0.10
...                      ...               ...           ...
27823                    NaN  2025-08-01 16:35          2.90
27824       2024-08-31 10:34  2024-08-31 10:12          0.01
27825       2024-07-04 18:15  2024-07-09 19:02        606.30
27826                    NaN  2024-10-06 15:15          0.40
27827                    NaN  2024-10-06 18:50          0.01

          FIRST_UC_DATE FIRST_UC_SIZE     FIRST_TO_DATE  FIRST_TO_SIZE  \
0      2006-04-02 22:00          0.01               NaN            NaN
1      2006-04-03 13:20          0.20               NaN            NaN
2      2006-04-03 13:23          0.50               NaN            NaN
3      2006-04-03 14:08          0.01               NaN            NaN
4      2006-04-03 20:19          0.10  2006-04-03 20:20            0.1
...                 ...           ...               ...            ...
27823  2025-08-01 17:20          2.90               NaN            NaN
27824  2024-08-31 11:00          0.01               NaN            NaN
27825  2024-07-10 17:50        606.30               NaN            NaN
27826  2024-10-06 15:18          0.40               NaN            NaN
27827  2024-10-06 18:50          0.01               NaN            NaN

          FIRST_EX_DATE FIRST_EX_SIZE_PERIMETER
0      2006-04-03 10:20                    0.10
1      2006-04-03 14:00                    0.20
2      2006-04-03 15:00                    0.50
3      2006-04-03 15:05                    0.01
4      2006-04-05 10:18                    0.10
...                 ...                     ...
27823  2025-08-02 10:56                    2.90
27824  2024-08-31 12:20                    0.01
27825  2024-09-11 13:48                  621.60
27826  2024-10-06 16:00                    0.22
27827  2024-10-07 10:00                    0.01

[27828 rows x 50 columns]>

In [4]:
df.columns.tolist()

['YEAR',
 'FIRE_NUMBER',
 'FIRE_NAME',
 'CURRENT_SIZE',
 'SIZE_CLASS',
 'LATITUDE',
 'LONGITUDE',
 'FIRE_ORIGIN',
 'GENERAL_CAUSE',
 'INDUSTRY_IDENTIFIER',
 'RESPONSIBLE_GROUP',
 'ACTIVITY_CLASS',
 'TRUE_CAUSE',
 'FIRE_START_DATE',
 'DETECTION_AGENT_TYPE',
 'DETECTION_AGENT',
 'DISCOVERED_DATE',
 'DISCOVERED_SIZE',
 'REPORTED_DATE',
 'DISPATCHED_RESOURCE',
 'DISPATCH_DATE',
 'START_FOR_FIRE_DATE',
 'ASSESSMENT_RESOURCE',
 'ASSESSMENT_DATETIME',
 'ASSESSMENT_HECTARES',
 'FIRE_SPREAD_RATE',
 'FIRE_TYPE',
 'FIRE_POSITION_ON_SLOPE',
 'WEATHER_CONDITIONS_OVER_FIRE',
 'TEMPERATURE',
 'RELATIVE_HUMIDITY',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'FUEL_TYPE',
 'INITIAL_ACTION_BY',
 'IA_ARRIVAL_AT_FIRE_DATE',
 'IA_ACCESS',
 'FIRE_FIGHTING_START_DATE',
 'FIRE_FIGHTING_START_SIZE',
 'BUCKETING_ON_FIRE',
 'DISTANCE_FROM_WATER_SOURCE',
 'FIRST_BUCKET_DROP_DATE',
 'FIRST_BH_DATE',
 'FIRST_BH_SIZE',
 'FIRST_UC_DATE',
 'FIRST_UC_SIZE',
 'FIRST_TO_DATE',
 'FIRST_TO_SIZE',
 'FIRST_EX_DATE',
 'FIRST_EX_SIZE_PERIMETER']

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
YEAR,27828.0,NaN,NaN,NaN,2014.70907,5.800447,2006.0,2010.0,2014.0,2020.0,2025.0
FIRE_NUMBER,27828,2548,PWF001,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE_NAME,876,270,,239,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CURRENT_SIZE,27828.0,NaN,NaN,NaN,262.268971,6379.773826,0.01,0.01,0.02,0.3,577646.8
SIZE_CLASS,27828,5,A,18280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LATITUDE,27828.0,NaN,NaN,NaN,55.021822,2.576318,48.998195,53.315733,55.344138,56.77125,59.99951
LONGITUDE,27828.0,NaN,NaN,NaN,-115.216704,2.356702,-119.999983,-116.83695,-115.1752,-114.278854,-110.000917
FIRE_ORIGIN,27816,7,Provincial Land,19808,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GENERAL_CAUSE,27828,15,Lightning,9746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDUSTRY_IDENTIFIER,513,11,Provincial,152,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RESPONSIBLE_GROUP,9663,32,Campers,4777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACTIVITY_CLASS,16852,34,Cooking and Warming,3670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRUE_CAUSE,14596,21,Unsafe Fire,5749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE_START_DATE,27109,21347,2012-05-21 12:00,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DETECTION_AGENT_TYPE,27828,5,UNP,12402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DETECTION_AGENT,27828,151,310,4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISCOVERED_DATE,21977,21071,2022-08-21 17:28,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISCOVERED_SIZE,152.0,NaN,NaN,NaN,18.000395,202.972156,0.0,0.01,0.01,0.1,2500.0
REPORTED_DATE,27828,26658,2006-07-01 17:39,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISPATCHED_RESOURCE,27813,7,HAC,12618,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISPATCH_DATE,27813,26665,2021-05-27 5:10,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
START_FOR_FIRE_DATE,27808,26686,2021-05-27 5:23,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASSESSMENT_RESOURCE,27827,4,IA Forces,23170,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASSESSMENT_DATETIME,27828,26942,2006-07-01 17:50,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASSESSMENT_HECTARES,27828.0,NaN,NaN,NaN,2.42986,58.704752,0.01,0.01,0.01,0.25,6019.0
FIRE_SPREAD_RATE,24970.0,NaN,NaN,NaN,0.90988,2.602409,-1.0,0.0,0.0,1.0,100.0
FIRE_TYPE,25178,5,Surface,18455,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE_POSITION_ON_SLOPE,24909,5,Flat,20373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WEATHER_CONDITIONS_OVER_FIRE,24903,5,Clear,11712,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TEMPERATURE,24901.0,NaN,NaN,NaN,17.878888,7.7845,-39.0,14.0,19.0,23.0,60.0
RELATIVE_HUMIDITY,24893.0,NaN,NaN,NaN,45.20327,18.675777,0.0,31.0,40.0,56.0,100.0
WIND_DIRECTION,24893,11,W,5670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WIND_SPEED,24893.0,NaN,NaN,NaN,8.92283,8.418009,0.0,3.0,7.0,12.0,90.0
FUEL_TYPE,20068,15,C2,7068,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INITIAL_ACTION_BY,27810,15,HAC,6202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IA_ARRIVAL_AT_FIRE_DATE,19690,18975,2006-07-01 17:48,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IA_ACCESS,12303,5,Conventional R/W,9014,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE_FIGHTING_START_DATE,19822,18956,2006-07-01 17:50,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE_FIGHTING_START_SIZE,19822.0,NaN,NaN,NaN,10.51827,202.360196,0.01,0.01,0.02,0.3,9999.0
BUCKETING_ON_FIRE,19622,3,N,11497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISTANCE_FROM_WATER_SOURCE,8119.0,NaN,NaN,NaN,2.448528,18.982628,0.0,0.5,1.0,2.0,700.0
FIRST_BUCKET_DROP_DATE,8120,7904,2006-07-01 18:35,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRST_BH_DATE,27828,26658,2008-04-09 15:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRST_BH_SIZE,27828.0,NaN,NaN,NaN,187.365964,6110.165013,0.01,0.01,0.02,0.3,602417.0
FIRST_UC_DATE,27828,26613,2008-04-09 15:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRST_UC_SIZE,27828.0,NaN,NaN,NaN,273.182818,7220.851534,0.01,0.01,0.02,0.3,707648.0
FIRST_TO_DATE,2856,2753,2008-04-09 15:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRST_TO_SIZE,2856.0,NaN,NaN,NaN,1.830333,13.2807,0.01,0.01,0.02,0.23,312.8
FIRST_EX_DATE,27812,26316,2008-04-18 12:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRST_EX_SIZE_PERIMETER,27812.0,NaN,NaN,NaN,244.101566,6264.795254,0.01,0.01,0.02,0.3,577646.8

In [6]:
df.isna().sum().sort_values(ascending=False)

DISCOVERED_SIZE                 27676
INDUSTRY_IDENTIFIER             27315
FIRE_NAME                       26952
FIRST_TO_SIZE                   24972
FIRST_TO_DATE                   24972
DISTANCE_FROM_WATER_SOURCE      19709
FIRST_BUCKET_DROP_DATE          19708
RESPONSIBLE_GROUP               18165
IA_ACCESS                       15525
TRUE_CAUSE                      13232
ACTIVITY_CLASS                  10976
BUCKETING_ON_FIRE                8206
IA_ARRIVAL_AT_FIRE_DATE          8138
FIRE_FIGHTING_START_DATE         8006
FIRE_FIGHTING_START_SIZE         8006
FUEL_TYPE                        7760
DISCOVERED_DATE                  5851
WIND_DIRECTION                   2935
RELATIVE_HUMIDITY                2935
WIND_SPEED                       2935
TEMPERATURE                      2927
WEATHER_CONDITIONS_OVER_FIRE     2925
FIRE_POSITION_ON_SLOPE           2919
FIRE_SPREAD_RATE                 2858
FIRE_TYPE                        2650
FIRE_START_DATE                   719
START_FOR_FIRE_DATE                20
INITIAL_ACTION_BY                  18
FIRST_EX_DATE                      16
FIRST_EX_SIZE_PERIMETER            16
DISPATCH_DATE                      15
DISPATCHED_RESOURCE                15
FIRE_ORIGIN                        12
ASSESSMENT_RESOURCE                 1
FIRST_BH_DATE                       0
CURRENT_SIZE                        0
SIZE_CLASS                          0
LATITUDE                            0
FIRST_UC_SIZE                       0
FIRST_UC_DATE                       0
FIRST_BH_SIZE                       0
FIRE_NUMBER                         0
LONGITUDE                           0
ASSESSMENT_HECTARES                 0
GENERAL_CAUSE                       0
DETECTION_AGENT_TYPE                0
DETECTION_AGENT                     0
REPORTED_DATE                       0
ASSESSMENT_DATETIME                 0
YEAR                                0
dtype: int64

In [7]:
df.nunique().sort_values()

BUCKETING_ON_FIRE                   3
ASSESSMENT_RESOURCE                 4
FIRE_POSITION_ON_SLOPE              5
SIZE_CLASS                          5
IA_ACCESS                           5
WEATHER_CONDITIONS_OVER_FIRE        5
FIRE_TYPE                           5
DETECTION_AGENT_TYPE                5
FIRE_ORIGIN                         7
DISPATCHED_RESOURCE                 7
WIND_DIRECTION                     11
INDUSTRY_IDENTIFIER                11
GENERAL_CAUSE                      15
INITIAL_ACTION_BY                  15
FUEL_TYPE                          15
YEAR                               20
DISCOVERED_SIZE                    21
TRUE_CAUSE                         21
RESPONSIBLE_GROUP                  32
ACTIVITY_CLASS                     34
FIRE_SPREAD_RATE                   57
WIND_SPEED                         68
RELATIVE_HUMIDITY                 101
DISTANCE_FROM_WATER_SOURCE        110
DETECTION_AGENT                   151
FIRST_TO_SIZE                     260
ASSESSMENT_HECTARES               262
FIRE_NAME                         270
TEMPERATURE                       353
FIRE_FIGHTING_START_SIZE          394
FIRST_BH_SIZE                    1026
FIRST_UC_SIZE                    1381
FIRST_EX_SIZE_PERIMETER          1651
CURRENT_SIZE                     1664
FIRE_NUMBER                      2548
FIRST_TO_DATE                    2753
FIRST_BUCKET_DROP_DATE           7904
FIRE_FIGHTING_START_DATE        18956
IA_ARRIVAL_AT_FIRE_DATE         18975
DISCOVERED_DATE                 21071
FIRE_START_DATE                 21347
LATITUDE                        25537
LONGITUDE                       25997
FIRST_EX_DATE                   26316
FIRST_UC_DATE                   26613
FIRST_BH_DATE                   26658
REPORTED_DATE                   26658
DISPATCH_DATE                   26665
START_FOR_FIRE_DATE             26686
ASSESSMENT_DATETIME             26942
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [9]:
df[df.duplicated()].head()

Empty DataFrame
Columns: [YEAR, FIRE_NUMBER, FIRE_NAME, CURRENT_SIZE, SIZE_CLASS, LATITUDE, LONGITUDE, FIRE_ORIGIN, GENERAL_CAUSE, INDUSTRY_IDENTIFIER, RESPONSIBLE_GROUP, ACTIVITY_CLASS, TRUE_CAUSE, FIRE_START_DATE, DETECTION_AGENT_TYPE, DETECTION_AGENT, DISCOVERED_DATE, DISCOVERED_SIZE, REPORTED_DATE, DISPATCHED_RESOURCE, DISPATCH_DATE, START_FOR_FIRE_DATE, ASSESSMENT_RESOURCE, ASSESSMENT_DATETIME, ASSESSMENT_HECTARES, FIRE_SPREAD_RATE, FIRE_TYPE, FIRE_POSITION_ON_SLOPE, WEATHER_CONDITIONS_OVER_FIRE, TEMPERATURE, RELATIVE_HUMIDITY, WIND_DIRECTION, WIND_SPEED, FUEL_TYPE, INITIAL_ACTION_BY, IA_ARRIVAL_AT_FIRE_DATE, IA_ACCESS, FIRE_FIGHTING_START_DATE, FIRE_FIGHTING_START_SIZE, BUCKETING_ON_FIRE, DISTANCE_FROM_WATER_SOURCE, FIRST_BUCKET_DROP_DATE, FIRST_BH_DATE, FIRST_BH_SIZE, FIRST_UC_DATE, FIRST_UC_SIZE, FIRST_TO_DATE, FIRST_TO_SIZE, FIRST_EX_DATE, FIRST_EX_SIZE_PERIMETER]
Index: []

[0 rows x 50 columns]

In [11]:
df.dtypes

YEAR                              int64
FIRE_NUMBER                      object
FIRE_NAME                        object
CURRENT_SIZE                    float64
SIZE_CLASS                       object
LATITUDE                        float64
LONGITUDE                       float64
FIRE_ORIGIN                      object
GENERAL_CAUSE                    object
INDUSTRY_IDENTIFIER              object
RESPONSIBLE_GROUP                object
ACTIVITY_CLASS                   object
TRUE_CAUSE                       object
FIRE_START_DATE                  object
DETECTION_AGENT_TYPE             object
DETECTION_AGENT                  object
DISCOVERED_DATE                  object
DISCOVERED_SIZE                 float64
REPORTED_DATE                    object
DISPATCHED_RESOURCE              object
DISPATCH_DATE                    object
START_FOR_FIRE_DATE              object
ASSESSMENT_RESOURCE              object
ASSESSMENT_DATETIME              object
ASSESSMENT_HECTARES             float64
FIRE_SPREAD_RATE                float64
FIRE_TYPE                        object
FIRE_POSITION_ON_SLOPE           object
WEATHER_CONDITIONS_OVER_FIRE     object
TEMPERATURE                     float64
RELATIVE_HUMIDITY               float64
WIND_DIRECTION                   object
WIND_SPEED                      float64
FUEL_TYPE                        object
INITIAL_ACTION_BY                object
IA_ARRIVAL_AT_FIRE_DATE          object
IA_ACCESS                        object
FIRE_FIGHTING_START_DATE         object
FIRE_FIGHTING_START_SIZE        float64
BUCKETING_ON_FIRE                object
DISTANCE_FROM_WATER_SOURCE      float64
FIRST_BUCKET_DROP_DATE           object
FIRST_BH_DATE                    object
FIRST_BH_SIZE                   float64
FIRST_UC_DATE                    object
FIRST_UC_SIZE                   float64
FIRST_TO_DATE                    object
FIRST_TO_SIZE                   float64
FIRST_EX_DATE                    object
FIRST_EX_SIZE_PERIMETER         float64
dtype: object

In [12]:
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)
missing[missing > 0]

DISCOVERED_SIZE                 27676
INDUSTRY_IDENTIFIER             27315
FIRE_NAME                       26952
FIRST_TO_SIZE                   24972
FIRST_TO_DATE                   24972
DISTANCE_FROM_WATER_SOURCE      19709
FIRST_BUCKET_DROP_DATE          19708
RESPONSIBLE_GROUP               18165
IA_ACCESS                       15525
TRUE_CAUSE                      13232
ACTIVITY_CLASS                  10976
BUCKETING_ON_FIRE                8206
IA_ARRIVAL_AT_FIRE_DATE          8138
FIRE_FIGHTING_START_DATE         8006
FIRE_FIGHTING_START_SIZE         8006
FUEL_TYPE                        7760
DISCOVERED_DATE                  5851
WIND_DIRECTION                   2935
RELATIVE_HUMIDITY                2935
WIND_SPEED                       2935
TEMPERATURE                      2927
WEATHER_CONDITIONS_OVER_FIRE     2925
FIRE_POSITION_ON_SLOPE           2919
FIRE_SPREAD_RATE                 2858
FIRE_TYPE                        2650
FIRE_START_DATE                   719
START_FOR_FIRE_DATE                20
INITIAL_ACTION_BY                  18
FIRST_EX_DATE                      16
FIRST_EX_SIZE_PERIMETER            16
DISPATCH_DATE                      15
DISPATCHED_RESOURCE                15
FIRE_ORIGIN                        12
ASSESSMENT_RESOURCE                 1
dtype: int64

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,27828.0,2014.709070,5.800447,2006.000000,2010.000000,2014.000000,2020.000000,2025.000000
CURRENT_SIZE,27828.0,262.268971,6379.773826,0.010000,0.010000,0.020000,0.300000,577646.800000
LATITUDE,27828.0,55.021822,2.576318,48.998195,53.315733,55.344138,56.771250,59.999510
LONGITUDE,27828.0,-115.216704,2.356702,-119.999983,-116.836950,-115.175200,-114.278854,-110.000917
DISCOVERED_SIZE,152.0,18.000395,202.972156,0.000000,0.010000,0.010000,0.100000,2500.000000
ASSESSMENT_HECTARES,27828.0,2.429860,58.704752,0.010000,0.010000,0.010000,0.250000,6019.000000
FIRE_SPREAD_RATE,24970.0,0.909880,2.602409,-1.000000,0.000000,0.000000,1.000000,100.000000
TEMPERATURE,24901.0,17.878888,7.784500,-39.000000,14.000000,19.000000,23.000000,60.000000
RELATIVE_HUMIDITY,24893.0,45.203270,18.675777,0.000000,31.000000,40.000000,56.000000,100.000000
WIND_SPEED,24893.0,8.922830,8.418009,0.000000,3.000000,7.000000,12.000000,90.000000
FIRE_FIGHTING_START_SIZE,19822.0,10.518270,202.360196,0.010000,0.010000,0.020000,0.300000,9999.000000
DISTANCE_FROM_WATER_SOURCE,8119.0,2.448528,18.982628,0.000000,0.500000,1.000000,2.000000,700.000000
FIRST_BH_SIZE,27828.0,187.365964,6110.165013,0.010000,0.010000,0.020000,0.300000,602417.000000
FIRST_UC_SIZE,27828.0,273.182818,7220.851534,0.010000,0.010000,0.020000,0.300000,707648.000000
FIRST_TO_SIZE,2856.0,1.830333,13.280700,0.010000,0.010000,0.020000,0.230000,312.800000
FIRST_EX_SIZE_PERIMETER,27812.0,244.101566,6264.795254,0.010000,0.010000,0.020000,0.300000,577646.800000

In [14]:
categorical_columns = [
    "SIZE_CLASS",
    "FIRE_ORIGIN",
    "GENERAL_CAUSE",
    "TRUE_CAUSE",
    "FIRE_TYPE",
    "FIRE_POSITION_ON_SLOPE",
    "FUEL_TYPE"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(15))

--- SIZE_CLASS ---
SIZE_CLASS
A    18280
B     7272
C     1344
E      525
D      407
Name: count, dtype: int64

--- FIRE_ORIGIN ---
FIRE_ORIGIN
Provincial Land       19808
Private Land           3949
Indian Reservation     3441
Provincial Park         315
Metis Settlement        168
DND                     133
NaN                      12
National Park             2
Name: count, dtype: int64

--- GENERAL_CAUSE ---
GENERAL_CAUSE
Lightning               9746
Recreation              5871
Resident                4640
Incendiary              2412
Power Line Industry     1543
Undetermined            1064
Agriculture Industry     727
Forest Industry          519
Oil & Gas Industry       489
Other Industry           341
Government               175
Railroad                 150
Under Investigation       67
Restart                   65
Prescribed Fire           19
Name: count, dtype: int64

--- TRUE_CAUSE ---
TRUE_CAUSE
NaN                    13232
Unsafe Fire             5749
Abandoned Fire          2084
Burning Substance       1280
Permit Related          1147
Line Impact              748
Winter Burning           652
Mechanical Failure       471
Arson Suspected          423
Unpredictable Event      363
Insufficient Buffer      361
Vehicle Fire             266
Friction Spark           265
Unclassified             211
Hot Exhaust              155
Name: count, dtype: int64

--- FIRE_TYPE ---
FIRE_TYPE
Surface       18455
Ground         5570
NaN            2650
Crown          1151
   Surface        1
                  1
Name: count, dtype: int64

--- FIRE_POSITION_ON_SLOPE ---
FIRE_POSITION_ON_SLOPE
Flat          20373
NaN            2919
Bottom         1492
Upper 1/3      1186
Middle 1/3     1009
Lower 1/3       849
Name: count, dtype: int64

--- FUEL_TYPE ---
FUEL_TYPE
NaN    7760
C2     7068
O1a    4410
M2     2565
O1b    2184
M1      743
C3      742
C1      606
S1      559
S2      510
D1      498
C4      151
C7       23
M3        4
C6        3
Name: count, dtype: int64

In [15]:
date_columns = [
    "FIRE_START_DATE",
    "DISCOVERED_DATE",
    "REPORTED_DATE",
    "DISPATCH_DATE",
    "ASSESSMENT_DATETIME",
    "IA_ARRIVAL_AT_FIRE_DATE",
    "FIRE_FIGHTING_START_DATE",
    "FIRST_BUCKET_DROP_DATE",
    "FIRST_BH_DATE",
    "FIRST_UC_DATE",
    "FIRST_TO_DATE",
    "FIRST_EX_DATE"
]

for column in date_columns:
    df[column] = pd.to_datetime(df[column], errors="coerce")

df[date_columns].dtypes

FIRE_START_DATE             datetime64[ns]
DISCOVERED_DATE             datetime64[ns]
REPORTED_DATE               datetime64[ns]
DISPATCH_DATE               datetime64[ns]
ASSESSMENT_DATETIME         datetime64[ns]
IA_ARRIVAL_AT_FIRE_DATE     datetime64[ns]
FIRE_FIGHTING_START_DATE    datetime64[ns]
FIRST_BUCKET_DROP_DATE      datetime64[ns]
FIRST_BH_DATE               datetime64[ns]
FIRST_UC_DATE               datetime64[ns]
FIRST_TO_DATE               datetime64[ns]
FIRST_EX_DATE               datetime64[ns]
dtype: object

In [16]:
numeric_columns = [
    "CURRENT_SIZE",
    "LATITUDE",
    "LONGITUDE",
    "TEMPERATURE",
    "RELATIVE_HUMIDITY",
    "WIND_SPEED"
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
CURRENT_SIZE,27828.0,262.268971,6379.773826,0.010000,0.010000,0.020000,0.300000,577646.800000
LATITUDE,27828.0,55.021822,2.576318,48.998195,53.315733,55.344138,56.771250,59.999510
LONGITUDE,27828.0,-115.216704,2.356702,-119.999983,-116.836950,-115.175200,-114.278854,-110.000917
TEMPERATURE,24901.0,17.878888,7.784500,-39.000000,14.000000,19.000000,23.000000,60.000000
RELATIVE_HUMIDITY,24893.0,45.203270,18.675777,0.000000,31.000000,40.000000,56.000000,100.000000
WIND_SPEED,24893.0,8.922830,8.418009,0.000000,3.000000,7.000000,12.000000,90.000000

In [17]:
invalid_coordinates = df[
    (df["LATITUDE"] < 48) |
    (df["LATITUDE"] > 60) |
    (df["LONGITUDE"] > -110) |
    (df["LONGITUDE"] < -121)
]

print("Potentially invalid coordinates:", len(invalid_coordinates))

Potentially invalid coordinates: 0

In [18]:
df["FIRE_NUMBER"].nunique()

2548

In [19]:
df["YEAR"].value_counts().sort_index()

YEAR
2006    1954
2007    1348
2008    1712
2009    1710
2010    1840
2011    1218
2012    1568
2013    1226
2014    1470
2015    1898
2016    1376
2017    1244
2018    1279
2019    1005
2020     723
2021    1342
2022    1276
2023    1132
2024    1230
2025    1277
Name: count, dtype: int64

In [20]:
df["GENERAL_CAUSE"].value_counts(dropna=False)

GENERAL_CAUSE
Lightning               9746
Recreation              5871
Resident                4640
Incendiary              2412
Power Line Industry     1543
Undetermined            1064
Agriculture Industry     727
Forest Industry          519
Oil & Gas Industry       489
Other Industry           341
Government               175
Railroad                 150
Under Investigation       67
Restart                   65
Prescribed Fire           19
Name: count, dtype: int64